# Q1:  elencare esami citati nella pubblicazione x
SELECT 
    E.ID AS ESAME
FROM
    ESAME E
        JOIN
    ESAME_has_PUBBLICAZIONE EP ON EP.ESAME_ID = E.ID
        JOIN
    PUBBLICAZIONE P ON EP.PUBBLICAZIONE_ID = P.ID
WHERE
    P.ID = '';
    

#Q2:  contare per ogni rivista quante pubblicazioni fanno riferimento ad esami svolti dopo il $$$$ (ANNO) (ANNO ESCLUSO)
SELECT 
    P.NOME_RIVISTA AS RIVISTA,
    COUNT(P.NOME_RIVISTA) AS NUMERO_PUBBLICAZIONI
FROM
    PUBBLICAZIONE P
        JOIN
    ESAME_has_PUBBLICAZIONE EP ON P.ID = EP.PUBBLICAZIONE_ID
        JOIN
    ESAME E ON EP.ESAME_ID = E.ID
WHERE
    YEAR(E.DATA)>2000
GROUP BY P.NOME_RIVISTA;

#ELENCO SOGGETTO E PATOLOGIA
SELECT 
    S.ID AS ID_SOGGETTO, P.ID AS PATOLOGIA_ID
FROM
    SOGGETTO S
        JOIN
    SOGGETTO_has_PATOLOGIA_DISABILITA_MOTORIA SP ON S.ID = SP.SOGGETTO_ID
        JOIN
    PATOLOGIA_DISABILITA_MOTORIA P ON SP.PATOLOGIA_DISABILITA_MOTORIA_ID = P.ID
UNION
SELECT 
    S.ID AS ID_SOGGETTO, P.ID AS PATOLOGIA_ID
FROM
    SOGGETTO S
        JOIN
    SOGGETTO_has_PATOLOGIA_DISABILITA_COGNITIVA SP ON S.ID = SP.SOGGETTO_ID
        JOIN
    PATOLOGIA_DISABILITA_COGNITIVA P ON SP.PATOLOGIA_DISABILITA_COGNITIVA_ID = P.ID ;


#Q3:  elencare esami fatti con il paradigma x su un paziente con patologia :
#CREO UNA VISTA CON LE DUE QUERY DI PRIMA
SELECT ID_SOGGETTO FROM SOGGETTO_PATOLOGIA;  #CONTROLLO LA VISTA

SELECT 
    E.ID AS CODICE_ESAME
FROM
    ESAME E
        JOIN
    P300 P ON E.P300_ID = P.ID
WHERE
    E.SOGGETTO_ID IN (SELECT 
            ID_SOGGETTO
        FROM
            SOGGETTO_PATOLOGIA);

#se ha patologia y:
SELECT ID_SOGGETTO FROM SOGGETTO_PATOLOGIA WHERE ID_PATOLOGIA=2;  #CONTROLLO LA VISTA RISPETTO ALLA PATOLOGIA CON ID 2

SELECT 
    E.ID AS CODICE_ESAME
FROM
    ESAME E
        JOIN
    P300 P ON E.P300_ID = P.ID
WHERE
    E.SOGGETTO_ID IN (SELECT 
            ID_SOGGETTO
        FROM
            SOGGETTO_PATOLOGIA
        WHERE
            ID_PATOLOGIA = 2);


#Q4:  elencare soggetti sui quali è stato fatto un esame con strumento risonanza
#1
SELECT 
    S.ID
FROM
    SOGGETTO S
        JOIN
    ESAME E ON S.ID = E.SOGGETTO_ID
WHERE
    E.RISONANZA_ID IS NOT NULL;
#2
SELECT 
    DS.SOGGETTO_ID AS ID, DS.NOME, DS.COGNOME, DS.CF
FROM
    DETTAGLIO_SOGGETTO DS
        JOIN
    ESAME E ON DS.SOGGETTO_ID = E.SOGGETTO_ID
WHERE
    E.RISONANZA_ID IS NOT NULL;

#3
SELECT 
    DS.SOGGETTO_ID AS ID, DS.NOME, DS.COGNOME, DS.CF
FROM
    DETTAGLIO_SOGGETTO DS
        JOIN
    SOGGETTO S ON DS.SOGGETTO_ID = S.ID
        JOIN
    ESAME E ON S.ID = E.SOGGETTO_ID
WHERE
    E.RISONANZA_ID IS NOT NULL;
    
#NOTA: forse ha senso rimuovere dettaglio soggetto (?)

#Q5:  
#PER OGNI ESAME, calcolare una media del benchmark per gli esami i cui soggetti sono sottoposti ad un trattamento farmacologico
#DA VEDERE SE HA SENSO
SELECT * FROM BENCHMARK;

SELECT 
    E.ID AS ESAME,
    AVG(BITRATE) AS MEDIA_BITRATE,
    AVG(ACCURATEZZA) AS MEDIA_ACCURATEZZA,
    AVG(ENTROPIA) AS MEDIA_ENTROPIA
FROM
    BENCHMARK B
        JOIN
    ESAME E ON B.ESAME_ID = E.ID
WHERE
    E.SOGGETTO_ID IN (SELECT 
            S.ID
        FROM
            SOGGETTO S
                JOIN
            TRATTAMENTO_FARMACOLOGICO T ON S.ID = T.SOGGETTO_ID)
GROUP BY ESAME_ID;

#calcolare una media del benchmark per gli esami i cui soggetti sono sottoposti ad un trattamento farmacologico
SELECT 
    AVG(BITRATE) AS MEDIA_BITRATE,
    AVG(ACCURATEZZA) AS MEDIA_ACCURATEZZA,
    AVG(ENTROPIA) AS MEDIA_ENTROPIA
FROM
    BENCHMARK B
        JOIN
    ESAME E ON B.ESAME_ID = E.ID
WHERE
    E.SOGGETTO_ID IN (SELECT 
            S.ID
        FROM
            SOGGETTO S
                JOIN
            TRATTAMENTO_FARMACOLOGICO T ON S.ID = T.SOGGETTO_ID);
            
#Q6:  quale è l’applicazione più comune per i pazienti con una determinata patologia
#BOH

SELECT TIPO, COUNT(*) AS FREQUENZA FROM APPLICAZIONE GROUP BY TIPO; #PER OGNI TIPO LA FREQUENZA DELLE APPLICAZIONI

#Q7:  contare il numero di esami per ogni paradigma (quanti esami ci sono con quel paradigma) 
#potremo anche selezionare solo quelli che hanno un benchmark maggiore di … 

#Q8: informazioni dei soggetti

SELECT * from DETTAGLIO_SOGGETTO AS SD WHERE SD.SOGGETTO_ID="" OR (SD.NOME="" AND SD.COGNOME="");

#Q9:  INSERIRE UN NUOVO ESAME ED UN NUOVO SOGGETTO

INSERT INTO ESAME VALUES("");
INSERT INTO SOGGETTO VALUES("");

#Q10:  TRATTAMENTO FAMACOLOGICO PASSATI DI UN DETERMINATO SOGGETTO CON ANNESSI DATI DEL SOGGETTO
SELECT * FROM TRATTAMENTO_FARMACOLOGICO;
SELECT 
    DS.SOGGETTO_ID, DS.NOME, DS.COGNOME, TF.NOME_MEDICINALE, TF.DATA_INIZIO, TF.DATA_FINE
FROM
    DETTAGLIO_SOGGETTO DS
        JOIN
    TRATTAMENTO_FARMACOLOGICO TF ON DS.SOGGETTO_ID = TF.SOGGETTO_ID 
    WHERE TF.DATA_FINE IS NOT NULL;
#POSSIAMO ANCHE FAR INSERIRE CODICE FSICALE O NOME E COGNOME 
SELECT * FROM TRATTAMENTO_FARMACOLOGICO;
SELECT 
    DS.SOGGETTO_ID, DS.NOME, DS.COGNOME, TF.NOME_MEDICINALE, TF.DATA_INIZIO, TF.DATA_FINE
FROM
    DETTAGLIO_SOGGETTO DS
        JOIN
    TRATTAMENTO_FARMACOLOGICO TF ON DS.SOGGETTO_ID = TF.SOGGETTO_ID 
    WHERE TF.DATA_FINE IS NOT NULL AND ((DS.NOME="" AND DS.COGNOME="") OR DS.CF="");
    
#Q11: NUMERO DI PUBBLIICAZIONI FATTE DA OGNI RICERCATORE NELL'ULTIMO ANNO

SELECT 
    R.ID,
    R.NOME,
    R.COGNOME,
    COUNT(PR.RICERCATORSOGGETTO_PATOLOGIASOGGETTOE_ID) AS NUMERO_PUBBLICAZIONI
FROM
    RICERCATORE R
        JOIN
    PUBBLICAZIONE_has_RICERCATORE PR ON R.ID = PR.RICERCATORE_ID
        JOIN
    PUBBLICAZIONE P ON PR.PUBBLICAZIONE_ID = P.ID
WHERE
    P.ANNO = 2022
GROUP BY R.ID
ORDER BY NUMERO_PUBBLICAZIONI;

#VEDERE DATO CHE FORSE NON HA SENSO

#Q12: RESOCONTO DELL'ESAME 56 E SENSORI NIRS UTILIZZATI SOLO IN CASO SIA UTILIZZATO UNO STRUMENTO NIRS
SELECT * FROM ESAME E JOIN NIRS N ON E.NIRS_ID=N.ID JOIN NIRS_has_SENSORE_NIRS NS ON N.ID=NS.NIRS_ID WHERE E.ID=56;

#INFORMAZIONI NECESSARIE ESAME E STRUMENTI CON SENSORI
SELECT E.ID AS ID_ESAME, E.DATA, E.SOGGETTO_ID, N.ID AS ID_STRUMENTO, NSN.NUMERO_SENSORI FROM ESAME E JOIN NIRS N ON E.NIRS_ID=N.ID JOIN NIRS_has_SENSORE_NIRS NSN ON N.ID=NSN.NIRS_ID
UNION 
SELECT E.ID AS ID_ESAME, E.DATA, E.SOGGETTO_ID, M.ID AS IS_STRUMENTO, MSM.NUMERO_SENSORI FROM ESAME E JOIN MEG M ON E.MEG_ID=M.ID JOIN MEG_has_SENSORE_MEG MSM ON M.ID=MSM.MEG_ID;


#Q13: MODIFICA STATO LICENZA  PER PAZIENTE CON ID 6547
UPDATE ESAME AS E SET E.LICENZA=1 WHERE E.SOGGETTO_ID=6547;

#Q14: PER UN SOGGETTO VEDERE QUALE TIPO DI PARADIGMA USATO E LE SUE SPECIFICHE, E LA MEDIA DEL BENCHMARK PER STABILIRNE L'ACCURATEZZA
SELECT E.ID AS ESAME_ID, P.PARADIGMA, P.NUMERO_CLASSI, B.MATRICE_CONFUSIONE, B.ACCURATEZZA, B.ENTROPIA, B.BITRATE FROM PARAMETRO P JOIN ESAME E ON P.ID=E.PARAMETRO_ID JOIN BENCHMARK B ON E.ID=B.ESAME_ID WHERE E.SOGGETTO_ID=1 ORDER BY E.DATA;




SELECT E.ID AS ID_ESAME FROM SOGGETTO_PATOLOGIA S JOIN ESAME E ON E.SOGGETTO_ID = S.ID_SOGGETTO JOIN ESAME_has_PARAMETRO EP ON E.ID = EP.ESAME_ID JOIN PARAMETRO P ON EP.PARAMETRO_ID = P.ID 
WHERE P.PARADIGMA = "CVEP" AND S.ID_PATOLOGIA="3";

SELECT A.TIPO, COUNT(A.TIPO) AS NUMERO_APPLICAZIONI
FROM APPLICAZIONE A JOIN ESAME E ON A.ID = E.APPLICAZIONE_ID JOIN SOGGETTO S ON S.ID = E.SOGGETTO_ID JOIN SOGGETTO_has_PATOLOGIA_DISABILITA_COGNITIVA SP ON SP.SOGGETTO_ID = S.ID 
GROUP BY A.TIPO;


SELECT 
    E.ID AS ESAME_ID,
    P.PARADIGMA,
    B.MATRICE_CONFUSIONE,
    B.ACCURATEZZA,
    B.ENTROPIA,
    B.BITRATE
FROM
    PARAMETRO P
    JOIN ESAME_has_PARAMETRO EP ON P.ID=EP.PARAMETRO_ID
        JOIN
    ESAME E ON E.ID = EP.ESAME_ID
        JOIN
    BENCHMARK B ON E.ID = B.ESAME_ID
WHERE
    E.SOGGETTO_ID = '+str(id)+'
ORDER BY E.DATA